# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(911, 703)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Packs = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Packs.sizePolicy().hasHeightForWidth())
        self.Packs.setSizePolicy(sizePolicy)
        self.Packs.setMinimumSize(QtCore.QSize(518, 94))
        self.Packs.setMaximumSize(QtCore.QSize(518, 94))
        self.Packs.setTabletTracking(False)
        self.Packs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Packs.setAutoFillBackground(False)
        self.Packs.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Packs.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Packs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Packs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Packs.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Packs.setAutoScroll(False)
        self.Packs.setDefaultDropAction(QtCore.Qt.TargetMoveAction)
        self.Packs.setSelectionMode(QtWidgets.QAbstractItemView.ContiguousSelection)
        self.Packs.setObjectName("Packs")
        self.Packs.setColumnCount(4)
        self.Packs.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Packs.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Packs.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Packs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Packs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Packs.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Packs.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Packs.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Packs.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Packs.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Packs.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Packs.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Packs.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Packs.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Packs.setItem(1, 3, item)
        self.Packs.horizontalHeader().setCascadingSectionResizes(False)
        self.Packs.horizontalHeader().setSortIndicatorShown(False)
        self.Packs.horizontalHeader().setStretchLastSection(False)
        self.Packs.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.Packs)
        self.Motor = QtWidgets.QTableWidget(Form)
        self.Motor.setMinimumSize(QtCore.QSize(235, 94))
        self.Motor.setMaximumSize(QtCore.QSize(235, 94))
        self.Motor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Motor.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Motor.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Motor.setObjectName("Motor")
        self.Motor.setColumnCount(1)
        self.Motor.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Motor.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Motor.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Motor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Motor.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.Motor.setItem(1, 0, item)
        self.Motor.horizontalHeader().setStretchLastSection(False)
        self.Motor.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.Motor)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TSI = QtWidgets.QTableWidget(Form)
        self.TSI.setMinimumSize(QtCore.QSize(342, 64))
        self.TSI.setMaximumSize(QtCore.QSize(342, 64))
        self.TSI.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TSI.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TSI.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.TSI.setObjectName("TSI")
        self.TSI.setColumnCount(3)
        self.TSI.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TSI.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.TSI.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.TSI.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.TSI.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.TSI.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.TSI.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.TSI.setItem(0, 2, item)
        self.TSI.horizontalHeader().setStretchLastSection(False)
        self.TSI.verticalHeader().setVisible(True)
        self.TSI.verticalHeader().setCascadingSectionResizes(False)
        self.TSI.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_2.addWidget(self.TSI)
        self.TSV = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TSV.sizePolicy().hasHeightForWidth())
        self.TSV.setSizePolicy(sizePolicy)
        self.TSV.setMinimumSize(QtCore.QSize(350, 64))
        self.TSV.setMaximumSize(QtCore.QSize(350, 64))
        self.TSV.setAutoFillBackground(False)
        self.TSV.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TSV.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TSV.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.TSV.setWordWrap(False)
        self.TSV.setObjectName("TSV")
        self.TSV.setColumnCount(3)
        self.TSV.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.TSV.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.TSV.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.TSV.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.TSV.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.TSV.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.TSV.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.TSV.setItem(0, 2, item)
        self.TSV.horizontalHeader().setStretchLastSection(False)
        self.TSV.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_2.addWidget(self.TSV)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.Packs.verticalHeaderItem(0)
        item.setText(_translate("Form", "Voltage (V)"))
        item = self.Packs.verticalHeaderItem(1)
        item.setText(_translate("Form", "Current (A)"))
        item = self.Packs.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Pack1"))
        item = self.Packs.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Pack2"))
        item = self.Packs.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Pack3"))
        item = self.Packs.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Pack4"))
        __sortingEnabled = self.Packs.isSortingEnabled()
        self.Packs.setSortingEnabled(False)
        item = self.Packs.item(0, 0)
        item.setText(_translate("Form", "Vpack1"))
        item = self.Packs.item(0, 1)
        item.setText(_translate("Form", "Vpack2"))
        item = self.Packs.item(0, 2)
        item.setText(_translate("Form", "Vpack3"))
        item = self.Packs.item(0, 3)
        item.setText(_translate("Form", "Vpack4"))
        item = self.Packs.item(1, 0)
        item.setText(_translate("Form", "Ipack1"))
        item = self.Packs.item(1, 1)
        item.setText(_translate("Form", "Ipack2"))
        item = self.Packs.item(1, 2)
        item.setText(_translate("Form", "Ipack3"))
        item = self.Packs.item(1, 3)
        item.setText(_translate("Form", "Ipack4"))
        self.Packs.setSortingEnabled(__sortingEnabled)
        item = self.Motor.verticalHeaderItem(0)
        item.setText(_translate("Form", "Temperature"))
        item = self.Motor.verticalHeaderItem(1)
        item.setText(_translate("Form", "Speed (RPM)"))
        item = self.Motor.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Motor"))
        __sortingEnabled = self.Motor.isSortingEnabled()
        self.Motor.setSortingEnabled(False)
        item = self.Motor.item(0, 0)
        item.setText(_translate("Form", "Tmotor"))
        item = self.Motor.item(1, 0)
        item.setText(_translate("Form", "Vmotor"))
        self.Motor.setSortingEnabled(__sortingEnabled)
        item = self.TSI.verticalHeaderItem(0)
        item.setText(_translate("Form", "TSI"))
        item = self.TSI.horizontalHeaderItem(0)
        item.setText(_translate("Form", "State"))
        item = self.TSI.horizontalHeaderItem(1)
        item.setText(_translate("Form", "IMD"))
        item = self.TSI.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Brake"))
        __sortingEnabled = self.TSI.isSortingEnabled()
        self.TSI.setSortingEnabled(False)
        item = self.TSI.item(0, 0)
        item.setText(_translate("Form", "TSI_State"))
        item = self.TSI.item(0, 1)
        item.setText(_translate("Form", "TSI-IMD"))
        item = self.TSI.item(0, 2)
        item.setText(_translate("Form", "TSI-Brake"))
        self.TSI.setSortingEnabled(__sortingEnabled)
        item = self.TSV.verticalHeaderItem(0)
        item.setText(_translate("Form", "TSV"))
        item = self.TSV.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Voltage(V)"))
        item = self.TSV.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Current(V)"))
        item = self.TSV.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Temp"))
        __sortingEnabled = self.TSV.isSortingEnabled()
        self.TSV.setSortingEnabled(False)
        item = self.TSV.item(0, 0)
        item.setText(_translate("Form", "Vtsv"))
        item = self.TSV.item(0, 1)
        item.setText(_translate("Form", "Itsv"))
        item = self.TSV.item(0, 2)
        item.setText(_translate("Form", "Ttsv"))
        self.TSV.setSortingEnabled(__sortingEnabled)

