# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(559, 633)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("background-color: rgb(130, 36, 51);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Motor = QtWidgets.QTableWidget(Form)
        self.Motor.setMinimumSize(QtCore.QSize(151, 86))
        self.Motor.setMaximumSize(QtCore.QSize(151, 86))
        self.Motor.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(0, 0, 0);")
        self.Motor.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Motor.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Motor.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Motor.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Motor.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Motor.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.Motor.setCornerButtonEnabled(False)
        self.Motor.setObjectName("Motor")
        self.Motor.setColumnCount(1)
        self.Motor.setRowCount(2)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Motor.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Motor.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.Motor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Motor.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Motor.setItem(1, 0, item)
        self.Motor.horizontalHeader().setMinimumSectionSize(17)
        self.Motor.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout.addWidget(self.Motor)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setMinimumSize(QtCore.QSize(102, 0))
        self.tableWidget.setMaximumSize(QtCore.QSize(102, 53))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(0, 0, 0);")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.TSI = QtWidgets.QTableWidget(Form)
        self.TSI.setMinimumSize(QtCore.QSize(332, 56))
        self.TSI.setMaximumSize(QtCore.QSize(332, 56))
        self.TSI.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"gridline-color: rgb(0, 0, 0);")
        self.TSI.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.TSI.setFrameShadow(QtWidgets.QFrame.Plain)
        self.TSI.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TSI.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.TSI.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.TSI.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.TSI.setCornerButtonEnabled(False)
        self.TSI.setObjectName("TSI")
        self.TSI.setColumnCount(3)
        self.TSI.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.TSI.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.TSI.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.TSI.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.TSI.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.TSI.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.TSI.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.TSI.setItem(0, 2, item)
        self.TSI.horizontalHeader().setStretchLastSection(False)
        self.TSI.verticalHeader().setVisible(True)
        self.TSI.verticalHeader().setCascadingSectionResizes(False)
        self.TSI.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.TSI, 0, QtCore.Qt.AlignHCenter)
        self.Packs = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Packs.sizePolicy().hasHeightForWidth())
        self.Packs.setSizePolicy(sizePolicy)
        self.Packs.setMinimumSize(QtCore.QSize(251, 176))
        self.Packs.setMaximumSize(QtCore.QSize(251, 176))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Packs.setFont(font)
        self.Packs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Packs.setAutoFillBackground(True)
        self.Packs.setStyleSheet("gridline-color: rgb(0, 0, 0);\n"
"selection-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);\n"
"QTableCornerButton::section {background-color: rgba(0,0,0,0);} ")
        self.Packs.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Packs.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Packs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Packs.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Packs.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Packs.setAutoScroll(False)
        self.Packs.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.Packs.setShowGrid(True)
        self.Packs.setCornerButtonEnabled(False)
        self.Packs.setObjectName("Packs")
        self.Packs.setColumnCount(2)
        self.Packs.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Packs.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Packs.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Packs.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Packs.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Packs.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Packs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.Packs.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Packs.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Packs.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Packs.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(13)
        item.setFont(font)
        self.Packs.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Packs.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Packs.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Packs.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Packs.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Packs.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Packs.setItem(4, 1, item)
        self.verticalLayout.addWidget(self.Packs, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.Motor.verticalHeaderItem(0)
        item.setText(_translate("Form", "Temp"))
        item = self.Motor.verticalHeaderItem(1)
        item.setText(_translate("Form", "Speed"))
        item = self.Motor.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Motor"))
        __sortingEnabled = self.Motor.isSortingEnabled()
        self.Motor.setSortingEnabled(False)
        item = self.Motor.item(0, 0)
        item.setText(_translate("Form", "Tmotor"))
        item = self.Motor.item(1, 0)
        item.setText(_translate("Form", "Vmotor"))
        self.Motor.setSortingEnabled(__sortingEnabled)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "name"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Session"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "some"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        item = self.TSI.verticalHeaderItem(0)
        item.setText(_translate("Form", "TSI"))
        item = self.TSI.horizontalHeaderItem(0)
        item.setText(_translate("Form", "State"))
        item = self.TSI.horizontalHeaderItem(1)
        item.setText(_translate("Form", "IMD"))
        item = self.TSI.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Temp"))
        __sortingEnabled = self.TSI.isSortingEnabled()
        self.TSI.setSortingEnabled(False)
        item = self.TSI.item(0, 0)
        item.setText(_translate("Form", "TSI_State"))
        item = self.TSI.item(0, 1)
        item.setText(_translate("Form", "TSI-IMD"))
        item = self.TSI.item(0, 2)
        item.setText(_translate("Form", "TSI-Temp"))
        self.TSI.setSortingEnabled(__sortingEnabled)
        item = self.Packs.verticalHeaderItem(0)
        item.setText(_translate("Form", "Pack1"))
        item = self.Packs.verticalHeaderItem(1)
        item.setText(_translate("Form", "Pack2"))
        item = self.Packs.verticalHeaderItem(2)
        item.setText(_translate("Form", "Pack3"))
        item = self.Packs.verticalHeaderItem(3)
        item.setText(_translate("Form", "Pack4"))
        item = self.Packs.verticalHeaderItem(4)
        item.setText(_translate("Form", "TSV"))
        item = self.Packs.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Voltage"))
        item = self.Packs.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Current"))
        __sortingEnabled = self.Packs.isSortingEnabled()
        self.Packs.setSortingEnabled(False)
        item = self.Packs.item(0, 0)
        item.setText(_translate("Form", "Vpack1"))
        item = self.Packs.item(0, 1)
        item.setText(_translate("Form", "Ipack1"))
        item = self.Packs.item(1, 0)
        item.setText(_translate("Form", "Vpack2"))
        item = self.Packs.item(1, 1)
        item.setText(_translate("Form", "Ipack2"))
        item = self.Packs.item(2, 0)
        item.setText(_translate("Form", "Vpack3"))
        item = self.Packs.item(2, 1)
        item.setText(_translate("Form", "Ipack3"))
        item = self.Packs.item(3, 0)
        item.setText(_translate("Form", "Vpack4"))
        item = self.Packs.item(3, 1)
        item.setText(_translate("Form", "Ipack4"))
        item = self.Packs.item(4, 0)
        item.setText(_translate("Form", "Vtsv"))
        item = self.Packs.item(4, 1)
        item.setText(_translate("Form", "Itsv"))
        self.Packs.setSortingEnabled(__sortingEnabled)

